version: '3'

networks:
  nginx-php-mysql-rabbitmq:

services:
  news-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: news-container
    ports:
    - "9001:9000"
    volumes:
    - ./app:/var/www/html/${APP_FOLDER_NAME}
    networks:
    - nginx-php-mysql-rabbitmq

  web-service:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
        - ./app:/var/www/html/${APP_FOLDER_NAME}
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - news-service
      - mysql-service
    networks:
      - nginx-php-mysql-rabbitmq

  mysql-service:
    image: mysql:8
    container_name: mysql-container
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  rabbit-service:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - nginx-php-mysql-rabbitmq
 
 
  cron-service:
    container_name: parse-news-cron
    build: ./cron
    volumes:
      - ../:/var/www
      - ./log/cron:/var/log/cron